# logtype can take: debug, info, notice, warning, error, critical
# warning is the default
logtype = "warning"

[config]
user = ""
password = ""
oldIpFile = "/var/lib/gonsupdate/oldIpFile"
ipv4 = true

[servertogetip]
urlList = ["http://www.icanhazip.com/", "https://ifconfig.co/ip", "https://ident.me", "https://curlmyip.net/"]

[email]
# Your email
from = ""
# Smtp of your email
smtp = ""
# SSL port
port = 587
# Your email login
login = ""
# Your email password
password = ""
# Who are send emails
sendTo = [""]
