# logtype can take: debug, info, notice, warning, error, critical
# warning is the default
logtype = "warning"

[config]
user = ""
password = ""
oldIpFile = "/var/lib/gonsupdate/oldIpFile"
ipv4 = true

[servertogetip]
urlList = ["http://curlmyip.com/", "http://www.icanhazip.com/"]
